language: node_js
node_js:
    - '10'
cache:
    directories:
        - node_modules
# before_deploy:
#     - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
script:
    - npm t
    - npm run lint
# deploy:
#     provider: script
#     script: "npm run lerna:publish-ci"
#     skip_cleanup: true
#     on:
#         tags: true
#         branch: master
